# Generated by Django 4.0.1 on 2022-01-30 17:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('active_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
