# Generated by Django 4.0.1 on 2022-02-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_customer_employee_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
